package com.sanyi.sanyiopc.utgard;

import com.sanyi.sanyiopc.bean.SocketFrame;
import org.nutz.json.Json;
import org.springframework.web.servlet.handler.WebRequestHandlerInterceptorAdapter;

public class getUtgard {

    public static void main(String[] args) throws Exception {
        String str = "{\n" +
                "   \"pumpdata\": [{\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterL\",\n" +
                "      \"unit\": \"M\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"液位\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterH\",\n" +
                "      \"unit\": \"M\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"扬程\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterF\",\n" +
                "      \"unit\": \"M\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"实时流量\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"IA\",\n" +
                "      \"unit\": \"A\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"电流IA\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"IC\",\n" +
                "      \"unit\": \"A\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"电流IC\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"IB\",\n" +
                "      \"unit\": \"A\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"电流IB\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"UA\",\n" +
                "      \"unit\": \"KV\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"电压UA\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"UB\",\n" +
                "      \"unit\": \"KV\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"电压UB\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"UC\",\n" +
                "      \"unit\": \"KV\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"电压UC\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"P\",\n" +
                "      \"unit\": \"KW\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"功率P\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Time_RunNow\",\n" +
                "      \"unit\": \"S\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"本次运行时间\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Time_Run\",\n" +
                "      \"unit\": \"S\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"累计运行时间\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterP1\",\n" +
                "      \"unit\": \"kpa\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"压力1\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterP2\",\n" +
                "      \"unit\": \"kpa\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"压力2\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock1\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动1\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock2\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动2\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock3\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动3\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock4\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动4\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock5\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动5\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock6\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动6\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock7\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动7\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Shock8\",\n" +
                "      \"unit\": \"mm/s\",\n" +
                "      \"group\": \"震动参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"震动8\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Pump_Allow_Remote\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"水泵允许远程控制\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Pump_Run\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"水泵运行反馈\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Pump_Stop\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"水泵停止反馈\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HV_TurnOff\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"高压柜分闸\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HV_TurnOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"高压柜合闸\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HV_IsON\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"高压柜合闸反馈\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HV_IsStop\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"高压柜停止反馈\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HV_IsErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"高压柜故障反馈\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"SV_TurnOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"软启启动\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"SV_TurnOff\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"软启停止\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"SV_IsON\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"软启柜启动反馈\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"SV_IsStop\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"软启柜停止反馈\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"SV_IsErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"软启柜故障反馈\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_TurnOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1开\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_TurnOff\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1关\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_IsOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1开启反馈\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_IsStop\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1停止反馈\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_TurnOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2开\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_TurnOff\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2关\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_IsOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2开启反馈\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_IsStop\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2停止反馈\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterP1_HErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"压力1高报警\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_LimitH3\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1开位信号3\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterL_LErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"低液位报警\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Temperature3\",\n" +
                "      \"unit\": \"C\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"温度3\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Temperature6\",\n" +
                "      \"unit\": \"C\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"温度6\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HDKS_TempErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"保护仪温度报警\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_IsErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2故障反馈\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_LimitH3\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2开位信号3\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterP2_HErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"压力2高报警\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_LimitH2\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2开位信号2\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_LimitH2\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1开位信号2\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Temperature4\",\n" +
                "      \"unit\": \"C\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"温度4\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve2_LimitH1\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门2开位信号1\",\n" +
                "      \"col\": \"5\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Temperature5\",\n" +
                "      \"unit\": \"C\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"温度5\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Temperature2\",\n" +
                "      \"unit\": \"C\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"温度2\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"WaterL_HErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"高液位报警\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_IsErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1故障反馈\",\n" +
                "      \"col\": \"2\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Temperature1\",\n" +
                "      \"unit\": \"C\",\n" +
                "      \"group\": \"运行参数\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"温度1\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"HDKS_ElecErr\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"故障状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"保护仪电导报警\",\n" +
                "      \"col\": \"3\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Valve1_LimitH1\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"设备状态反馈\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"阀门1开位信号1\",\n" +
                "      \"col\": \"4\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Pump_TurnOn\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"水泵自动启动\",\n" +
                "      \"col\": \"1\"\n" +
                "   }, {\n" +
                "      \"pname\": \"GX_YTH_Pump_1\",\n" +
                "      \"name\": \"Pump_TurnOff\",\n" +
                "      \"unit\": \"B\",\n" +
                "      \"group\": \"控制状态\",\n" +
                "      \"pumpname\": \"合肥市高新区一体化泵站-1#泵\",\n" +
                "      \"cname\": \"水泵自动停止\",\n" +
                "      \"col\": \"1\"\n" +
                "   }],\n" +
                "   \"type\": \"select\"\n" +
                "}";
        SocketFrame socketFrame = new SocketFrame();
        socketFrame = Json.fromJson(SocketFrame.class, str);
        Utgard utgard = new Utgard();
        while (true){
            Thread.sleep(500);
            System.out.println("!====!"+Json.toJson(utgard.utgard2(socketFrame)));
        }
    }
}
